[package]
name = "iroh_gossip_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
data-encoding = "2.9.0"
futures-lite = "2.6.0"
iroh = "0.34.1"
iroh-gossip = "0.34.1"
rand = "0.8"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = "1.44.2"
